language: go
sudo: false
go:
  - 1.5.3
  - tip

before_install:
  - go get golang.org/x/tools/cmd/cover

script:
  - go vet -x ./...
  - go test -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
